name: CI-CD
run-name: Testing out ci/cd

on: [push]
jobs:
  Install-dependencies-and-supertests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install client dependencies
        run: npm install
        working-directory: client

      - name: Install server dependencies
        run: npm install
        working-directory: server

      - name: Supertest run
        run: |
          cd server
          npm test

  # Cypress-e2e-test:
  #   runs-on: ubuntu-22.04

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Cypress-run-e2e
  #       uses: cypress-io/github-action@v6
  #       with:
  #         working-directory: client
  #         build: npm run build
  #         start: npm start

  Cypress-component-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress-run-components
        uses: cypress-io/github-action@v6
        with:
          working-directory: client
          component: true